export const authors = [
  "John Ray", "Wayne Gretzky", "Friedrich Nietzsche", "Ella Wheeler Wilcox", "Abraham Lincoln", "Audrey Hepburn", "Horace Mann", "Carol Burnett", "Erma Bombeck", "Patrick Henry", "Dolly Parton", "Mother Teresa", "Michelangelo", "Oprah Winfrey", "Charlie Chaplin", "Dale Carnegie", "George Bernard Shaw", "Amelia Earhart", "Elie Wiesel", "Alexandria Ocasio-Cortez", "Queen Elizabeth II", "George Washington", "Benjamin Franklin", "Muhammad Ali", "J.R.R. Tolkien", "Pablo Picasso", "Toni Morrison", "Leonardo Da Vinci",
  "Albert Einstein", "Joe Namath", "Dr. Seuss", "Dalai Lama", "Eckhart Tolle", "Indira Gandhi", "Heraclitus", "Walt Disney", "Mark Twain", "Oscar Wilde", "Isaac Newton", "Nelson Mandela", "Jean-Jacques Rousseau", "George Washington", "David Bowie", "Princess Diana", "Charlie Chaplin", "Norman Vincent Peale", "Liza Minelli", "Socrates", "Eleanor Roosevelt", "Malcolm X", "Mahatma Gandhi", "Henry D Thoreau", "Hugh Blair", "Muhammad Ali", "Albert Camus", "Ernest Hemingway", "Fyodor Dostoevsky", "Bruce Lee",

  "Robin Williams", "Katharine Hepburn", "Lao Tzu", "Kamala Harris", "Babe Ruth", "Anais Nin", "Desmond Tutu", "Christopher Reeve", "Ernesto 'Che' Guevara", "Henry Ford", "Anne Frank", "Eartha Kitt", "Aesop", "Geoffrey Chaucer", "Steve Jobs", "Georgia O'Keeffe", "Ernest Hemingway", "Douglas MacArthur", "Amanda Gorman", "Mark Twain", "Franklin D Roosevelt", "Lord Acton", "Maya Angelou", "Susan B. Anthony", "Abraham Lincoln", "George Orwell", "Ella Wheeler Wilcox", "Carol Burnett", "Howard W. Newton", "J.K. Rowling", "Alfred Tennyson",
  "Hillary Clinton", "George Orwell", "Voltaire", "Ansel Adams", "Percy Bysshe Shelley", "Timothy Leary", "Confucius", "Charles Dickens", "Margaret Atwood", "Albert Camus", "Bruce Lee", "Marie Curie", "Malcolm X", "Margaret Thatcher", "Franz Kafka", "Eleanor Roosevelt",
  "Antoine de Saint Exupéry", "Emily Bronte", "Elizabeth Taylor", "Julie Taymor", "Pyotr Tchaikovsky", "Shirley Temple", "Margaret Wolfe Hungerford", "Eckhart Tolle", "Lily Tomlin", "Neil Armstrong", "William Mountford", "Socrates", "Babe Ruth", "Pablo Picasso", "Napoleon Hill", "Katharine Lee Bates", "Samuel Johnson", "Aesop", "D.H. Lawrence", "J.K. Rowling", "Stanislaw Jerzy Lec", "John Dewey", "Alphonse Karr", "Otto von Bismarck", "Henry David Thoreau", "Charles Dickens", "Charlotte Bronte", "Timothy Leary", "John B. Soule", "John Ruskin", "Henry David Thoreau", "Lewis Carroll", "Matthew Arnold", "Queen Elizabeth II", "Lauren Bacall", "John Sherman", "Richard Franck", "Friedrich Nietzsche", "Mark Twain", "Robert Louis Stevenson", "Adolph Ochs", "Anatole France", "Thomas Edison", "Ella Wheeler Wilcox", "Dr. Seuss",
  "Friedrich Nietzsche", "Pratibha Patil", "Edith Wharton", "Rosa Parks", "Nicholas Murray Butler", "George Santayana", "Lester B Pearson", "Dolly Parton", "Boris Pasternak", "Hugh Wilson",

  "O Henry", "Sylvia Plath", "Sidney Poitier", "Federico Fellini", "Amelia Earhart", "Anne Frank",
  "Martha Washington", "Helen Keller", "Jane Wagner", "Joel Grey", "Edith Cavell", "Woody Guthrie", "Sue Grafton", "Katherine Paterson", "Brad Pitt", "George Orwell", "Alan Greenspan", "Thomas Edison", "Elizabeth Gilbert", "Malcolm Gladwell", "William Shakespeare",

  "Lilian GIsh", "Lucretius", "Mahatma Gandhi", "Tom Heehler", "Martha Graham", "Francis Ford Coppola/Mario Puzo", "Maya Angelou", "Napoleon Hill", "Malala Yousafzai", "Lucretius", "John McCrae", "Maxim Gorky", "Ralph Waldo Emerson", "Alexander Pope", "Voltaire", "George Santayana",

  "Sri Chinmoy", "Isaac Asimov", "Edith Wharton", "Pelé", "Dorothy Espelage", "Julian Assange", "Albert Einstein", "Abraham Lincoln", "Brenda Donald", "John Leguizamo", "Vincent Van Gogh", "Brian Eno", "Betty Ford", "Cicero", "Ronald Reagan",

  "Barack Obama", "Philip James Bailey", "Henri-Frédéric Amiel", "Robert Fulghum", "Anais Nin", "Cleveland/Benson/Gaye", "Natalie Portman", "Haile Selassie I", "Khalil Gibran", "Helen Keller", "Napoleon Hill", "Babe Ruth",

  "Ralph Waldo Emerson", "Franz Liszt", "Voltaire", "Albert Einstein", "Anne Murray", "Boris Pasternak", "Honoré de Balzac", "Pablo Picasso", "Bertrand Russell", "Meryl Streep", "Clement Clarke Moore", "Valentine Davies", "John Ruskin",

]