export const QUOTES = [
  "the early bird catches the worm", "you miss one hundred percent of the shots you don\u0027t take", "that which does not kill us makes us stronger", "a weed is but an unloved flower", "the ballot is stronger than the bullet", "the best thing to hold onto in life is each other", "a house without books is like a room without windows", "comedy is tragedy, plus time", "never have more children than you have car windows", "united we stand, divided we fall", "it costs a lot of money to look this cheap", "peace begins with a smile", "genius is eternal patience", "turn your wounds into wisdom", "we think too much and feel too little", "when fate hands you a lemon, make lemonade", "youth is wasted on the young", "adventure is worthwhile in itself", "the opposite of love is not hate, it\u0027s indifference", "our democracy is designed to speak truth to power", "grief is the price we pay for love", "it is better to be alone than in bad company", "remember that time is money", "float like a butterfly, sting like a bee", "not all those who wander are lost", "good artists copy, great artists steal", "if you surrendered to the air, you could ride it", "nothing strengthens authority so much as silence",
  "in the middle of difficulty lies opportunity", "if you aren\u0027t going all the way, why go at all", "i meant what i said and i said what i meant", "be kind whenever possible, it is always possible", "the only thing you ever have is now", "you can\u0027t shake hands with a clenched fist", "there is nothing permanent except change", "it\u0027s fun to do the impossible", "the secret of getting ahead is getting started", "be yourself, everyone else is already taken", "what goes up must come down", "it always seems impossible until it is done", "man was born free, and he is everywhere in chains", "worry is the interest paid by those who borrow trouble", "tomorrow belongs to those who can hear it coming", "only do what your heart tells you", "you\u0027ll never find a rainbow if you\u0027re looking down", "change your thoughts and you change the world", "my mother gave me my drive, but my father gave me my dreams", "to find yourself, think for yourself", "do one thing everyday that scares you", "a man who stands for nothing will fall for anything", "where there is love there is life", "the bluebird carries the sky on his back", "anxiety is the poison of human life", "don\u0027t count the days, make the days count", "an intellectual is someone whose mind watches itself", "there is no friend as loyal as a book", "to live without hope is to cease to live", "showing off is the fool\u0027s idea of glory",

  "canada is like a loft apartment over a really great party", "if you obey all the rules, you miss all the fun", "the journey of a thousand miles begins with one step", "the american dream belongs to all of us", "never let the fear of striking out get in your way", "life shrinks or expands in relation to one\u0027s courage", "without forgiveness, there\u0027s no future", "once you choose hope, anything is possible", "better to die standing than live on your knees", "whether you believe you can do something or not, you are right", "whoever is happy will make others happy too", "i am the original material girl", "it is easy to be brave from a safe distance", "many a true word is spoken in jest", "stay hungry, stay foolish", "the days you work are the best days", "never confuse movement with action", "old soldiers never die, they just fade away", "whenever i listen to songs, i rewrite them in my head", "wrinkles should merely indicate where smiles have been", "the only thing we have to fear is fear itself", "absolute power corrupts absolutely", "try to be a rainbow in someone\u0027s cloud", "independence is happiness", "actions speak louder than words", "history is written by the winners", "a poor original is better than a good imitation", "words, once they are printed, have a life of their own", "tact is the art of making a point without making an enemy", "i really don\u0027t believe in magic either", "love will conquer at the last",
  "showing up is not all of life but it counts for a lot", "man is the only real enemy we have", "one always speaks badly when one has nothing to say", "for me the future of the image is going to be in electronic form", "fame is love disguised", "think for yourself and question authority", "to study and not think is a waste", "ask no questions and you\u0027ll be told no lies", "war is what happens when language fails", "if the world were clear, art would not exist", "you are master of your attitude", "be less curious about people and more curious about ideas", "america\u0027s conscience is bankrupt", "the rule of law must prevail over the rule of the mob", "there is hope, but not for us", "example is the best lesson there is",
  "what is essential is invisible to the eye", "proud people breed sad sorrows for themselves", "there\u0027s no deodorant like success", "if you don\u0027t have fear then you are not taking a chance", "what i need is to believe in myself again", "i stopped believing in santa claus when i was six", "beauty is in the eye of the beholder", "awareness is the greatest agent for change", "nobody is here without a reason", "one small step for man, one giant leap for mankind", "be still my beating heart", "the unexamined life is not worth living", "you just can\u0027t beat the person who never gives up", "art is a lie that makes us realize truth", "there is no substitute for honesty", "from sea to shining sea", "of the blessings set before you, make your choice and be content", "no act of kindness, no matter how small, is ever wasted", "i could curse for hours and hours", "it does not do to dwell on dreams and forget to live", "no snowflake in an avalanche ever feels responsible", "art expresses, it does not state", "the more things change, the more they stay the same", "politics is not an exact science", "the bluebird carries the sky on his back", "it was the best of times, it was the worst of times", "unromantic as monday morning", "the universe is an intelligence test", "go west, young man", "there is no wealth but life", "to be awake is to be alive", "you\u0027re nothing but a pack of cards", "truth sits upon the lips of dying men", "grief is the price we pay for love", "the world doesn\u0027t owe you a damn thing", "i have come home to look after my fences", "necessity is the mother of invention", "there are no facts, only interpretations", "when in doubt, tell the truth", "the cruelest lies are often told in silence", "all the news that\u0027s fit to print", "lovers who love truly do not write down their happiness", "i\u0027d put my money on the sun and solar power", "laugh and the world laughs with you, weep and you weep alone", "don\u0027t cry because it\u0027s over, smile because it happened",
  "distrust all in whom the impulse to punish is powerful", "corruption is the enemy of development", "the only way not to think about money is to have a great deal of it", "i did not get on the bus to get arrested", "an expert is one who knows more and more about less and less", "those who cannot remember the past are condemned to repeat it", "politics is the skilled use of blunt objects", "do not confuse dreams with wishes", "only individuals seek the truth", "as god as my witness, i thought turkeys could fly",

  "turn up the lights, i don\u0027t want to go home in the dark", "i desire the things which will destroy me in the end", "the older we get the less afraid we are", "it\u0027s not what we say but how we say it that matters", "please know that i am aware of the hazards", "i want to go on living even after my death",
  "i am only fond of what comes from the heart", "the highest result of education is tolerance", "remember we are all in this alone", "stick with it, be who you are", "i must have no hatred or bitterness towards anyone", "this machine kills facists", "no one with a happy childhood ever amounts to much in this world", "even a prince may be a fool", "you shouldn\u0027t speak until you know what you're talking about", "big brother is watching you", "the world is governed by market forces", "our greatest weakness lies in giving up", "happiness is the consequence of personal effort", "those who lie outside of ordinary experience have the most to teach us", "double, double toil and trouble fire burn and cauldron bubble",

  "if you\u0027re caught acting, no one believes you", "the fall of dropping water wears away the stone", "a man is but the product of his thoughts", "courage is the ability to ignore your options", "to me, the only sin is mediocrity", "keep your friends close and your enemies closer", "you can\u0027t use up creativity", "quick riches are more dangerous than poverty", "education is one of the blessings of life", "life is one long struggle in the dark", "in flanders fields the poppies blow", "just as science is the intellect of the world, art is its soul", "the only way to have a good friend is to be one", "hope springs eternal in the human breast", "to hold a pen is to be at war", "the highest form of vanity is love of fame",

  "those who run after happiness will never be happy", "we cannot afford enemies any more", "there is no such thing as old age, there is only sorrow", "i was born for soccer", "children are not born cruel", "if wars can be started with lies, they can be stopped by truth", "imagination is more important than knowledge", "i am nothing, but truth is everything", "nothing matters more to a child than a place to call home", "education is the first step to empowerment", "i dream my painting and then i paint my dream", "when technology makes it perfect, art loses", "being ladylike does not require silence", "the law is silent during war", "it\u0027s the disease that\u0027s frightening, not the people who have it",

  "the peace we seek in the world begins in human hearts", "respect is what we owe, love what we give", "the man who has no inner life is the slave of his surroundings", "love the battle between chaos and imagination", "each friend represents a world in us", "war is not the answer for only love can conquer hate", "our job as actors is empathy", "leadership does not mean domination", "beauty is eternity gazing at itself in a mirror", "tolerance is the first principle of community", "there is no hope for the person who is dishonest", "every strike brings me closer to the next home run",

  "nothing can bring you peace but yourself", "wasting time is one of the worst faults of the world", "man is free at the instant he wants to be", "peace cannot be kept by force", "success of any kind is the result of hard work", "the powers of darkness will be crushed by the spirit of light", "the more a man judges, the less he loves", "it takes a very long time to become young", "the good life is one inspired by love and guided by knowledge", "we can all sense a mysterious connection to each other", "the stockings were hung by the chimney with care", "christmas isn't just a day, it\u0027s a frame of mind", "every increased possession loads us with a new weariness",

  "peace does not simply mean the absence of conflict", "love the sinner and hate the sin", "respect is a stepping stone to empathy", "nothing can come of nothing", "life is not life at all without delight", "ring out the old, ring in the new", "no person may enjoy outstanding success without good health", "it\u0027s much harder to be relevant than it is to be successful", "if i have seen further it is only by standing on the shoulders of giants", "if music be the food of love, play on", "if you can learn to read, you can learn almost anything", "for me, every hour is grace", "language alone is meditation", "life is the dancer and you are the dance", "i took my power in my hand and went against the world", "there is no such thing as slow freedom",

  "for every laugh, there should be a tear", "compassion and tolerance are not a sign of weakness but a sign of strength", "it is very beautiful over there", "to sit alone with my conscience will be judgement enough for me",

  "hope awakens courage", "war is what happens when language fails", "while there\u0027s life, there is hope", "the more we love the richer life is", "running water never grows stale", "without forgiveness there is no future",
]